[build]
  # Specifichiamo che il sito da buildare è nella cartella website
  base = "website"
  command = "npm run build"
  publish = ".next"

[functions]
  # Usciamo da website per trovare le funzioni comuni
  directory = "../netlify/functions"

[dev]
  # Next.js di solito usa la porta 3000
  command = "npm run dev"
  targetPort = 3000
  port = 8888

# Mantieni le tue funzioni programmate così come sono
[functions.pulizia-chiusure]
  schedule = "0 3 * * 1"